### ISSUE TITLE
Devtools wont work on debugger, works on 

### ISSUE THREAD

**Issue by LaloHao** [jhen0409/remotedev-rn-debugger#29]
If i go into `http://localhost:8081/debugger-ui/` the monitor does not do anything (no state, no actions dispatches), but if i go `http://localhost:8000/` everything works fine.

There are logs in the debugger indicating something
```
Console was cleared
23:55:58.746 Running application with appParams: {"rootTag":91}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
23:55:59.736 connected to remotedev-server
23:57:03.968 WebSocket connection to 'ws://localhost:8081/socketcluster/' failed: WebSocket is closed before the connection is established.
23:58:23.968 WebSocket connection to 'ws://localhost:8081/socketcluster/' failed: WebSocket is closed before the connection is established
```

Is there a way to debug this problem?

I also need to manually especify the default port and hostname, otherwise the server at `http://localhost:8000/` won't work 
`remotedev-debugger --hostname localhost --port 8000 --injectserver`

**Comment by LaloHao** [comment]
More info:

On the terminal:
```
1512722765526 - Origin: Worker (PID 21025)
   [Warning] SocketProtocolError: Client pong timed out
    at SCSocket._onSCClose (/Users/hao/dev/catedral/node_modules/socketcluster-server/scsocket.js:205:17)
    at Timeout.<anonymous> (/Users/hao/dev/catedral/node_modules/socketcluster-server/scsocket.js:170:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

adb logcat:
```
W/unknown:ReactNative( 3797): Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["websocketMessage",{"data":"#1","type":"text","id":1}])
```

**Comment by crs2here** [comment]
@LaloHao were you able to ever to debug on a physical device? I am running into the same problem
