### ISSUE TITLE
µWebSockets/UWS Error

### ISSUE THREAD

**Issue by mkchx** [jhen0409/remotedev-rn-debugger#30]
Hello,

I'm trying to run  Redux DevTools for a react native application of mine.
I'm getting an exception on `npm start`

```
PASS Inject RemoteDev server into React Native local server.
PASS Inject RemoteDev monitor into React Native debugger.
npm start
Scanning folders for symlinks in ...\node_modules (71ms)
[RemoteDev] Start server...
--------------------------------------------------------------------------------

   [Busy] Launching SocketCluster
1521031685340 - Origin: Worker (PID 7076)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (...\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (...\node_modules\uws\uws.js:42:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at new SCServer (...\node_modules\socketcluster-server\scserver.js:98:18)
1521031685357 - Worker 0 exited - Exit code: 1
1521031685645 - Origin: Worker (PID 14976)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (...\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (...\node_modules\uws\uws.js:42:3)
```
and it keeps going..
I used a boilerplate called [ignite](https://github.com/infinitered/ignite)
and here's the `package.json`

```
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force",
    "clean:android": "cd android/ && ./gradlew clean && cd .. && react-native run-android",
    "newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && npm i",
    "test:watch": "jest --watch",
    "updateSnapshot": "jest --updateSnapshot",
    "coverage": "jest --coverage && open coverage/lcov-report/index.html || xdg-open coverage/lcov-report/index.html",
    "android:build": "cd android && ./gradlew assembleRelease",
    "android:install": "cd android && ./gradlew assembleRelease && ./gradlew installRelease",
    "android:hockeyapp": "cd android && ./gradlew assembleRelease && puck -submit=auto app/build/outputs/apk/app-release.apk",
    "android:devices": "$ANDROID_HOME/platform-tools/adb devices",
    "android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
    "android:shake": "$ANDROID_HOME/platform-tools/adb devices | grep '\\t' | awk '{print $1}' | sed 's/\\s//g' | xargs -I {} $ANDROID_HOME/platform-tools/adb -s {} shell input keyevent 82",
    "storybook": "storybook start -p 7007",
    "postinstall": "remotedev-debugger --hostname localhost --port 8000 --injectserver"
  },
  "dependencies": {
    "apisauce": "^0.14.3",
    "format-json": "^1.0.3",
    "identity-obj-proxy": "^3.0.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.5",
    "nonce-generator": "^1.0.2",
    "prop-types": "^15.6.1",
    "querystringify": "^1.0.0",
    "ramda": "^0.25.0",
    "react": "^16.2.0",
    "react-native": "^0.54.1",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "^0.17.4",
    "react-native-dialogs": "0.0.21",
    "react-native-i18n": "^2.0.12",
    "react-native-material-ui": "^1.20.0",
    "react-native-push-notification": "^3.0.2",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-store": "^0.4.1",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.5.2",
    "react-navigation-redux-helpers": "^1.0.3",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "reduxsauce": "^0.7.0",
    "seamless-immutable": "^7.1.3"
  },
  "devDependencies": {
    "@storybook/addon-storyshots": "^3.3.15",
    "@storybook/addons": "^3.3.15",
    "@storybook/channels": "^3.3.15",
    "@storybook/react-native": "^3.3.15",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-jest": "^22.4.1",
    "babel-plugin-ignite-ignore-reactotron": "^0.3.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react-native": "^4.0.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.18.2",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-flowtype": "^2.46.1",
    "eslint-plugin-import": "^2.6.1",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.7.0",
    "husky": "^0.14.3",
    "ignite-ir-boilerplate": "^2.3.1",
    "ignite-redux-devtools": "^0.0.2",
    "jest": "^22.4.2",
    "mockery": "^2.1.0",
    "prettier": "1.11.1",
    "react-dom": "^16.2.0",
    "react-test-renderer": "^16.2.0",
    "reactotron-react-native": "^1.14.0",
    "reactotron-redux": "^1.13.0",
    "reactotron-redux-saga": "^1.13.0",
    "remote-redux-devtools": "^0.5.12",
    "remotedev-rn-debugger": "^0.8.3"
  },
  "jest": {
    "testMatch": [
      "<rootDir>/Tests/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "<rootDir>/Tests/Setup.js"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    },
    "setupFiles": [
      "<rootDir>/Tests/Setup"
    ],
    "preset": "react-native"
  },
  "config": {}
}

```

I've tried deleting the node_modules folder and `npm install with cache` clean too but nothing works
Maybe I'm missing something?

Thanks in advance.

**Comment by alvelig** [comment]
That's an upstream error. See what's in node_modules/uws/build_log.txt and act accordingly (rebuild and reinstall)

**Comment by xdays** [comment]
@mkchx do you resolve the problem now? I come across same problem.

My `node_modules/uws/build_log.txt`:

```
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
  CXX(target) Release/obj.target/uws/src/Networking.o
  CXX(target) Release/obj.target/uws/src/Hub.o
  CXX(target) Release/obj.target/uws/src/Node.o
  CXX(target) Release/obj.target/uws/src/WebSocket.o
  CXX(target) Release/obj.target/uws/src/HTTPSocket.o
  CXX(target) Release/obj.target/uws/src/Socket.o
  CXX(target) Release/obj.target/uws/src/addon.o
In file included from ../src/addon.cpp:2:
../src/addon.h:21:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, noop), 0, nullptr);
              ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:37:47: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            utf8Value = new (utf8ValueMemory) String::Utf8Value(value);
                                              ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/addon.cpp:2:
../src/addon.h:163:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(sc->isolate, sc->isolate->GetCurrentContext()->Global(), Local<Function>::New(sc->isolate, sc->jsCallback), 0, nullptr);
              ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:339:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *errorCallback), 1, argv);
              ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:3:
../src/http.h:31:115: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                    args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) header.value, String::kNormalString, header.valueLength));
                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:45:104: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "GET", String::kNormalString, 3));
                                                                                                       ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:48:104: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "PUT", String::kNormalString, 3));
                                                                                                       ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:51:105: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "POST", String::kNormalString, 4));
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:54:105: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "HEAD", String::kNormalString, 4));
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:57:106: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "PATCH", String::kNormalString, 5));
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:60:106: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "TRACE", String::kNormalString, 5));
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:63:107: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "DELETE", String::kNormalString, 6));
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:66:108: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "OPTIONS", String::kNormalString, 7));
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:69:108: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) "CONNECT", String::kNormalString, 7));
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:99:77: error: no matching member function for call to 'NewInstance'
            Local<Object> reqObjectLocal = reqTemplateLocal->GetFunction()->NewInstance();
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
In file included from ../src/addon.cpp:3:
../src/http.h:102:30: warning: 'SetNamedPropertyHandler' is deprecated [-Wdeprecated-declarations]
            headersTemplate->SetNamedPropertyHandler(Request::headers);
                             ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:5812:3: note: 'SetNamedPropertyHandler' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/addon.cpp:3:
../src/http.h:149:39: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
                    for (int i = 0; i < headers->Length(); i++) {
                                    ~ ^ ~~~~~~~~~~~~~~~~~
../src/http.h:196:53: error: no matching member function for call to 'NewInstance'
            return resTemplateLocal->GetFunction()->NewInstance();
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
In file included from ../src/addon.cpp:3:
../src/http.h:227:108: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
            reqObject->SetInternalField(4, String::NewFromOneByte(isolate, (uint8_t *) req.getUrl().value, String::kNormalString, req.getUrl().valueLength));
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:2737:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../src/addon.cpp:3:
../src/http.h:293:110: error: no matching member function for call to 'NewInstance'
            args.GetReturnValue().Set(newInstance = Local<Function>::New(args.GetIsolate(), httpPersistent)->NewInstance());
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
In file included from ../src/addon.cpp:3:
../src/http.h:320:159: error: too few arguments to function call, expected 2, have 1
            express->Get(String::NewFromUtf8(isolate, "request"))->ToObject()->SetPrototype(Local<Object>::New(args.GetIsolate(), reqTemplate)->GetPrototype());
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                   ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3308:3: note: 'SetPrototype' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
  ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8config.h:410:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/addon.cpp:3:
../src/http.h:321:160: error: too few arguments to function call, expected 2, have 1
            express->Get(String::NewFromUtf8(isolate, "response"))->ToObject()->SetPrototype(Local<Object>::New(args.GetIsolate(), resTemplate)->GetPrototype());
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                   ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3308:3: note: 'SetPrototype' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
  ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8config.h:410:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/addon.cpp:3:
../src/http.h:327:48: error: no matching member function for call to 'NewInstance'
            args.GetReturnValue().Set(express->NewInstance());
                                      ~~~~~~~~~^~~~~~~~~~~
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/xdays/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
In file included from ../src/addon.cpp:2:
../src/addon.h:256:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *connectionCallback), 1, argv);
              ^
../src/addon.h:441:48: note: in instantiation of function template specialization 'onConnection<true>' requested here
        NODE_SET_METHOD(group, "onConnection", onConnection<isServer>);
                                               ^
../src/addon.cpp:8:58: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "server"), Namespace<uWS::SERVER>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:324:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *disconnectionCallback), 4, argv);
              ^
../src/addon.h:443:51: note: in instantiation of function template specialization 'onDisconnection<true>' requested here
        NODE_SET_METHOD(group, "onDisconnection", onDisconnection<isServer>);
                                                  ^
../src/addon.cpp:8:58: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "server"), Namespace<uWS::SERVER>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:288:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *pingCallback), 2, argv);
              ^
../src/addon.h:454:42: note: in instantiation of function template specialization 'onPing<true>' requested here
        NODE_SET_METHOD(group, "onPing", onPing<isServer>);
                                         ^
../src/addon.cpp:8:58: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "server"), Namespace<uWS::SERVER>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:304:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *pongCallback), 2, argv);
              ^
../src/addon.h:455:42: note: in instantiation of function template specialization 'onPong<true>' requested here
        NODE_SET_METHOD(group, "onPong", onPong<isServer>);
                                         ^
../src/addon.cpp:8:58: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "server"), Namespace<uWS::SERVER>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:256:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *connectionCallback), 1, argv);
              ^
../src/addon.h:441:48: note: in instantiation of function template specialization 'onConnection<false>' requested here
        NODE_SET_METHOD(group, "onConnection", onConnection<isServer>);
                                               ^
../src/addon.cpp:9:58: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "client"), Namespace<uWS::CLIENT>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:324:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *disconnectionCallback), 4, argv);
              ^
../src/addon.h:443:51: note: in instantiation of function template specialization 'onDisconnection<false>' requested here
        NODE_SET_METHOD(group, "onDisconnection", onDisconnection<isServer>);
                                                  ^
../src/addon.cpp:9:58: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "client"), Namespace<uWS::CLIENT>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:288:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *pingCallback), 2, argv);
              ^
../src/addon.h:454:42: note: in instantiation of function template specialization 'onPing<false>' requested here
        NODE_SET_METHOD(group, "onPing", onPing<isServer>);
                                         ^
../src/addon.cpp:9:58: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "client"), Namespace<uWS::CLIENT>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cpp:2:
../src/addon.h:304:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(), Local<Function>::New(isolate, *pongCallback), 2, argv);
              ^
../src/addon.h:455:42: note: in instantiation of function template specialization 'onPong<false>' requested here
        NODE_SET_METHOD(group, "onPong", onPong<isServer>);
                                         ^
../src/addon.cpp:9:58: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
    exports->Set(String::NewFromUtf8(isolate, "client"), Namespace<uWS::CLIENT>(isolate).object);
                                                         ^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/xdays/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
14 warnings and 17 errors generated.
make: *** [Release/obj.target/uws/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xdays/Downloads/expo/crypto-tracker/node_modules/uws
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by alvelig** [comment]
@xdays downgrade to 8.9.4

**Comment by berenerchamion** [comment]
Same thing here on macOS...downgrading opens a slew of security vulnerabilities...

**Comment by iqqmuT** [comment]
https://github.com/zalmoxisus/remotedev-server/issues/58
This could be fixed by passing new option `--wsEngine=ws` to remotedev.

**Comment by iqqmuT** [comment]
It works now if you use PR above and pass option `--wsengine ws`, example `package.json`:
```
"postinstall": "remotedev-debugger --hostname localhost --port 5678 --injectserver --wsengine ws
```

**Comment by hqaisrani-apigarage** [comment]
@iqqmuT and for anyone else facing this issue. If you simply use the actual argument `wsEngine`, then there is no need for the PR.

Therefore, your script could look something like tjhis
```
"postinstall": "remotedev-debugger --hostname localhost --port 5678 --injectserver --wsEngine ws",
```
